# Generated by Django 3.2 on 2023-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(max_length=256, verbose_name='Название произведения'),
        ),
    ]
